### ISSUE TITLE
Not working in 4.1.0

### ISSUE THREAD

**Issue by adrianobr** [heriet/redmine-selectbox-autocompleter#19]
NoMethodError: undefined method `to_prepare' for ActionDispatch::Callbacks:Class
Did you mean?  to_param
/usr/src/redmine/plugins/selectbox_autocompleter/init.rb:24:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
/usr/src/redmine/lib/redmine/plugin.rb:181:in `block in load'
/usr/src/redmine/lib/redmine/plugin.rb:172:in `each'
/usr/src/redmine/lib/redmine/plugin.rb:172:in `load'
/usr/src/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `load'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `block in load'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `load'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/engine.rb:663:in `block in load_config_initializer'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/notifications.rb:170:in `instrument'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/engine.rb:662:in `load_config_initializer'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/engine.rb:619:in `each'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/engine.rb:619:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/initializable.rb:50:in `each'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/application.rb:361:in `initialize!'
/usr/src/redmine/config/environment.rb:16:in `<top (required)>'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/application.rb:337:in `require'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/application.rb:337:in `require_environment!'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'

**Comment by asyahana-icsp** [comment]
追記失礼します。
私も同環境においてプラグインを適用しようとして失敗しました。
お手数をおかけしますが、回避策等がございましたらご教授お願い致します。

Environment:
  Redmine version                4.1.1.stable.19716
  Ruby version                   2.5.3-p105 (2018-10-18) [x86_64-linux]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               Mysql2（MariaDB 10.4 with Mroonga）
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem

**Comment by adrianobr** [comment]
news?

**Comment by asyahana-icsp** [comment]
No, this is additional information about what this plugin doesn't work in Redmine Ver.4.1.0.

**Comment by sbrdiag** [comment]
私はinit.rbを以下のように修正してRedmine4.1にインストール成功しました。

init.rb
（bofore）
ActionDispatch::Callbacks.to_prepare do
（after）
ActiveSupport::Reloader.to_prepare do

**Comment by luizjr** [comment]
Hi, @heriet will this plugin support version 5 of Redmine?

**Comment by JGallot** [comment]
HI,
for using redmine 5
there is a fork here https://github.com/asannou/redmine-selectbox-autocompleter but don't allow pushing issues

Mine is here : https://github.com/JGallot/redmine-selectbox-autocompleter

**Comment by heriet** [comment]
Sorry for late.

Merged https://github.com/heriet/redmine-selectbox-autocompleter/pull/21

It works latest Redmine 5.0.5.
